### ISSUE TITLE
11

### ISSUE THREAD

**Issue by zhenxing123** [lee-zq/3DUNet-Pytorch#30]
你好，为什么在读取数据的时候，无法读取？报下面的错：
Traceback (most recent call last):
  File "E:/PytorchProject/3DUNet-Pytorch-master/dataset/dataset_lits_train.py", line 67, in <module>
    for i, (ct, seg) in enumerate(train_dl):
  File "D:\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "D:\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "D:\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "D:\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\_utils.py", line 434, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\PytorchProject\3DUNet-Pytorch-master\dataset\dataset_lits_train.py", line 29, in __getitem__
    ct = sitk.ReadImage(self.filename_list[index][0], sitk.sitkInt16)
  File "D:\Anaconda3\envs\pytorch_gpu\lib\site-packages\SimpleITK\extra.py", line 346, in ReadImage
    return reader.Execute()
  File "D:\Anaconda3\envs\pytorch_gpu\lib\site-packages\SimpleITK\SimpleITK.py", line 8015, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: D:\a\1\sitk\Code\IO\src\sitkImageReaderBase.cxx:97:
sitk::ERROR: The file "E:/Pytorch" does not exist.

**Comment by xinxinlly** [comment]
请问这个问题是如何解决的？
